# Generated by Django 5.0.1 on 2024-01-10 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YayaWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField()),
                ('cause', models.CharField(default='Testing', max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('invoice_url', models.URLField()),
            ],
        ),
    ]
